server:
  port: 9002

spring:
  application:
    name: ncov_base

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.1.58/panda?characterEncoding=utf-8&useSSL=false
    username: root
    password: ynu1325lab
  jpa:
    database: mysql
    show-sql: true